platform :ios, '10.0'
use_frameworks!

source 'git@github.com:zhang232425/ZJSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'ZJHUD_Example' do
  
  pod 'ZJHUD', :path => '../'
  
  pod 'ZJExtension',         :git => 'git@github.com:zhang232425/ZJExtension.git', :branch => 'main'

end
